### ISSUE TITLE
Probably incompatible branding firmware (German provider Telekom)

### ISSUE THREAD

**Issue by leachimus** [ZTETool/ZTE-MU5001-HACK#11]
Hello,

i have a branded device and I think that a restricted firmware is installed here, which does not have the hidden menus at all. So the functions are probably missing completely because they are not displayed.

Does anyone else have a german Telekom branded device and can confirm this or is there a way to install a global firmware? I have the version with LAN port.

The firmware version is
HW version:MU5001V1.0.0
WEB version:WEB_DTDEMU5001V1.0.0B09
WA INNER version:MU5001V1.0.0B11
from 23.02.2023

Would be nice if someone could help.

**Comment by the-harry** [comment]
Hi @leachimus, I'm sorry for the late reply; I managed to fry my router, so I left this project a bit aside. 

If I get my hands on a working version or if someone makes it available via [binwalk](https://github.com/ReFirmLabs/binwalk), we could perhaps get a working iso that supports this code so you could manually install on it as an update file even though it might brick it; hope it helps; perhaps someone else might be able to help on this one, I'd do the image myself if I haven't burnt it 😢  

Fingers crossed, we can get a working image and a list of supported devices and versions.

I'd happily contribute to this project, even though I should have been more timely. :)

**Comment by the-harry** [comment]
Hey, @leachimus, I've called for help on the README; let's see if someone gets it! 🤞🏻 


https://github.com/ZTETool/ZTE-MU5001-HACK/commit/97788a44132baa9cc29fd4333df38a969d323721

**Comment by the-harry** [comment]
Sorry, actually, if we could use this issue:

https://github.com/ZTETool/ZTE-MU5001-HACK/issues/6

I already intended to track such things there; if you could repost your hardware details there just to have it it would be great! I'll update the readme and close this issue for now so we can focus only here.

**Comment by leachimus** [comment]
They reply 10 months later and then apologise. That is not helpful.

You can forget about this matter. I now use a different product.

Goodbye.

**Comment by the-harry** [comment]
No worries. Sorry about that. All the best!

**Comment by anolkrghosh** [comment]
did anyone gets hand on root shell ???
or can anyone confirm if its root shell available vai usb ir uart only

**Comment by the-harry** [comment]
Hi @anolkrghosh, I don't think so, this project has never got to this point. The origin of this is simply some hidden menus on the UI which this repo shows in a better way along with the charts, but root access is out of scope.
